export interface GlossaryTerm {
  term: string;
  short: string;
  related?: string;
}

export const GLOSSARY: GlossaryTerm[] = [
  { term: "AIF", short: "Alternative Investment Fund — SEBI-regulated pooled vehicle with ₹1 Cr minimum. Three categories: I (startups/infra), II (PE/RE/debt), III (hedge).", related: "/investment-products/aif" },
  { term: "AMC", short: "Asset Management Company — the firm that manages mutual fund schemes (HDFC AMC, ICICI Prudential, etc.)." },
  { term: "AMFI", short: "Association of Mutual Funds in India — the self-regulatory organisation that maintains the ARN registry and industry standards." },
  { term: "AUM", short: "Assets Under Management — total value of assets a fund or manager handles. Often used as a proxy for credibility, but not infallible." },
  { term: "Bond yield", short: "The annual return on a bond, expressed as percentage. Inversely related to bond prices — when prices fall, yields rise." },
  { term: "CAGR", short: "Compound Annual Growth Rate — the smoothed annual growth rate of an investment over a period. The most useful single number for long-term return comparison." },
  { term: "Capital gain", short: "Profit from selling an asset for more than you paid. Taxed as short-term or long-term depending on holding period." },
  { term: "CIN", short: "Corporate Identification Number — unique 21-character identifier for every company registered in India." },
  { term: "DTAA", short: "Double Tax Avoidance Agreement — bilateral tax treaty preventing the same income from being taxed twice across two countries." },
  { term: "Demat", short: "Dematerialised — electronic form of holding shares and securities. Required for trading on Indian exchanges." },
  { term: "Direct plan", short: "A mutual fund variant with no distributor commission — saves 0.5-1% per year vs Regular plan. Buy via Coin, Kuvera, MFCentral, or AMC directly." },
  { term: "ELSS", short: "Equity Linked Savings Scheme — tax-saving mutual fund under Section 80C with 3-year lock-in (shortest of all 80C options)." },
  { term: "EPF", short: "Employees' Provident Fund — mandatory savings for salaried employees, with 8.25% (current) tax-free returns on employee + employer contributions." },
  { term: "ETF", short: "Exchange Traded Fund — a mutual fund that trades on the stock exchange like a stock. Often the cheapest way to track an index." },
  { term: "Expense ratio", short: "Annual fee charged by a mutual fund as % of AUM. Index funds: 0.1-0.5%. Active funds: 1-2%. Higher fees = lower net returns over decades." },
  { term: "FATCA", short: "US tax law requiring foreign financial institutions to report on US persons' accounts. Relevant for NRIs in the US who hold Indian investments." },
  { term: "FCNR", short: "Foreign Currency Non-Resident account — NRI deposit account in USD/GBP/etc. Repatriable, no currency risk." },
  { term: "FEMA", short: "Foreign Exchange Management Act — governs cross-border investment flows for Indian residents and NRIs." },
  { term: "FIRE", short: "Financial Independence, Retire Early — saving aggressively to build a corpus that lets you stop working long before traditional retirement age.", related: "/resources/calculators/fire" },
  { term: "Folio", short: "An account number assigned to a mutual fund investor by an AMC. You can have multiple folios within one AMC — best to consolidate." },
  { term: "GIFT City", short: "Gujarat International Finance Tec-City — India's IFSC, offering tax benefits on certain financial activities for non-residents and specific structures." },
  { term: "Goal-based investing", short: "Approach where each goal (retirement, kid's college, home) gets its own portfolio with appropriate horizon and risk." },
  { term: "Hurdle rate", short: "The minimum return a PMS or AIF must achieve before charging a performance fee. Common: 6-10%." },
  { term: "Index fund", short: "Mutual fund that passively tracks an index (Nifty 50, Sensex). Low cost, no manager risk, beats most active funds over 10+ years." },
  { term: "Indexation", short: "Adjusting cost basis for inflation when computing long-term capital gains. Removed from most debt funds after April 2023." },
  { term: "InvIT", short: "Infrastructure Investment Trust — listed vehicle holding income-producing infrastructure (power, roads, telecom). Like REIT but for infra." },
  { term: "IRA", short: "Individual Retirement Account — US tax-advantaged retirement account. Relevant for NRIs in the US." },
  { term: "ITR", short: "Income Tax Return — annual filing with Indian tax department. Different forms for different income types (ITR-1 through ITR-7)." },
  { term: "LTCG", short: "Long Term Capital Gains — gains on assets held beyond the defined long-term period (12 months for equity, 24 months for debt/real estate/unlisted)." },
  { term: "Lumpsum", short: "One-time investment vs SIP (monthly). For large amounts, STP from a liquid fund into target equity over 6-12 months often beats deploying all at once.", related: "/resources/calculators/lumpsum" },
  { term: "Mutual fund", short: "Pooled investment vehicle where investor money is collectively invested in a basket of securities managed by a professional fund manager.", related: "/investment-products/mutual-funds" },
  { term: "NAV", short: "Net Asset Value — per-unit value of a mutual fund, calculated daily based on the value of underlying holdings minus expenses." },
  { term: "NPS", short: "National Pension System — government-backed retirement scheme with tax benefits under 80C and 80CCD(1B). Equity exposure up to 75% allowed." },
  { term: "NRE", short: "Non-Resident External account — NRI rupee account where deposits come from foreign income. Fully repatriable, interest tax-free in India." },
  { term: "NRI", short: "Non-Resident Indian — Indian citizen residing outside India. Has specific tax and investment rules under FEMA and IT Act.", related: "/for/nri" },
  { term: "NRO", short: "Non-Resident Ordinary account — NRI rupee account for India-source income (rent, dividends, pension). Limited repatriability, interest taxable." },
  { term: "PE ratio", short: "Price to Earnings — a stock's price divided by its annual earnings per share. Quick valuation gauge, but should be compared within sector and over time." },
  { term: "PFIC", short: "Passive Foreign Investment Company — US tax classification for foreign mutual funds. Punitive tax regime — relevant for NRIs in US holding Indian MFs." },
  { term: "PPF", short: "Public Provident Fund — government scheme with 15-year lock-in, tax-free returns (currently 7.1%), and 80C deduction." },
  { term: "PMS", short: "Portfolio Management Service — SEBI-regulated managed account with ₹50L minimum, where you own stocks directly in demat.", related: "/investment-products/pms" },
  { term: "REIT", short: "Real Estate Investment Trust — listed vehicle holding income-producing commercial real estate. Distributes 90%+ of income to unitholders." },
  { term: "RIA", short: "Registered Investment Adviser — SEBI category for fee-only investment advisers (no commissions). Different from distributors (who earn from products)." },
  { term: "Risk profile", short: "Investor's tolerance for market volatility and capital loss. Determines target asset allocation between equity, debt, and other assets." },
  { term: "Sensex", short: "BSE Sensitive Index — 30 large-cap Indian stocks, India's oldest equity benchmark." },
  { term: "SEBI", short: "Securities and Exchange Board of India — the regulator for Indian capital markets, mutual funds, PMS, AIF, and investment advisers." },
  { term: "SGB", short: "Sovereign Gold Bond — government-issued bond denominated in grams of gold. Pays 2.5% interest plus gold price appreciation. LTCG-exempt if held to maturity." },
  { term: "SIP", short: "Systematic Investment Plan — fixed amount invested monthly into a mutual fund. Enforces discipline; averages purchase cost over time.", related: "/resources/calculators/sip" },
  { term: "STP", short: "Systematic Transfer Plan — periodic transfer from one mutual fund (typically liquid) to another (typically equity). Smooths deployment of lumpsum." },
  { term: "STCG", short: "Short Term Capital Gains — gains on assets held less than the long-term period. Higher tax rates than LTCG." },
  { term: "SWP", short: "Systematic Withdrawal Plan — fixed monthly withdrawal from a mutual fund. Common retirement income strategy." },
  { term: "Tax harvesting", short: "Selling and re-buying units to realise long-term capital gains within the annual ₹1.25L LTCG exemption, permanently saving 12.5% tax on those gains.", related: "/blog/ltcg-125-lakh-exemption-most-underused-tax-tool" },
  { term: "Term insurance", short: "Pure life insurance with no investment component. Pays out if you die during the term. Cheapest form of life cover.", related: "/investment-products/insurance" },
  { term: "TWRR", short: "Time-Weighted Rate of Return — strategy-level return that strips out the timing of cashflows. Used to compare PMS/fund manager performance across investors." },
  { term: "ULIP", short: "Unit Linked Insurance Plan — hybrid product combining insurance and investment. Generally underperforms term + MF combination after charges." },
  { term: "Unlisted shares", short: "Shares of companies not yet listed on stock exchanges. Includes pre-IPO and private equity. Typically ₹50k+ tickets, held in your own demat account.", related: "/investment-products/unlisted-shares" },
  { term: "VDA", short: "Virtual Digital Asset — Indian tax law category covering cryptocurrencies and NFTs. Taxed at 30% flat with 1% TDS over ₹50k/yr." },
  { term: "Yield", short: "Annual income from an investment as % of its current price. Dividend yield, bond yield, rental yield are common variants." },
];
